# Generated by Django 4.2.25 on 2025-10-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
