# Generated by Django 5.2.10 on 2026-01-07 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_alter_playermatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='opponent_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MatchFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_won', models.BooleanField(null=True)),
                ('h2h_win_ratio_diff', models.FloatField(default=0.0)),
                ('h2h_recent_momentum', models.FloatField(default=0.0)),
                ('recent_form_diff', models.FloatField(default=0.0)),
                ('win_rate_diff', models.FloatField(default=0.0)),
                ('serve_rating_diff', models.FloatField(default=0.0)),
                ('bp_conv_pctg_diff', models.FloatField(default=0.0)),
                ('dom_ratio_diff', models.FloatField(default=0.0)),
                ('fatigue_diff', models.FloatField(default=0.0)),
                ('match_volume_14d_diff', models.FloatField(default=0.0)),
                ('win_rate_hard_diff', models.FloatField(blank=True, null=True)),
                ('win_rate_clay_diff', models.FloatField(blank=True, null=True)),
                ('win_rate_grass_diff', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='tennis.playermatch')),
            ],
            options={
                'verbose_name': 'Match Training Data',
                'verbose_name_plural': 'Match Training Data',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_reg_prob', models.FloatField(null=True)),
                ('log_reg_amer', models.IntegerField(null=True)),
                ('log_reg_dec', models.FloatField(null=True)),
                ('rf_prob', models.FloatField(null=True)),
                ('rf_amer', models.IntegerField(null=True)),
                ('rf_dec', models.FloatField(null=True)),
                ('ens_prob', models.FloatField(null=True)),
                ('ens_amer', models.IntegerField(null=True)),
                ('ens_dec', models.FloatField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.playermatch')),
            ],
        ),
    ]
