# Generated by Django 4.2.25 on 2025-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_player_a_m_player_break_p_saved_pctg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ranking',
            field=models.FloatField(),
        ),
    ]
