# Generated by Django 5.2.10 on 2026-01-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_alter_playermatch_opponent_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfeatures',
            name='player_win_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
